on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v.0.9.0
        with: 
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: connect and deploy
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && ./deploy.sh"
